## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: R
cache: packages
#sudo: false

r:
#  - oldrel
  - release
  - devel

warnings_are_errors: true

env:
  global:
    - R_BUILD_ARGS="--no-resave-data"
